apiVersion: apps/v1
kind: Deployment
metadata:
  #Unique key of the Deployment instance
  name: my-fist-app

#Deployment specification  
spec:
  #3 Pods should exist at all times
  replicas: 3
  selector:
    matchLabels:
      app: first-app
  template: 
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-app
        image: roshanchaturpale/html-doc:latest
        
