apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fist-app
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-app
  template: 
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-container-app
        image: roshanchaturpale/html-doc:01
        
