apiVersion: apps/v1
kind: Deployment
metadata:
  #Unique key of the Deployment instance
  name: mongo-app

#Deployment specification  
spec:
  #2 Pods should exist at all times
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  template: 
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: mongo:latest


---


apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
  
spec:
  selector:
    app: mongo-app
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
  # type: LoadBalancer  
