apiVersion: apps/v1
kind: Deployment
metadata:
  #Unique key of the Deployment instance
  name: my-nodedb-app

#Deployment specification  
spec:
  #2 Pods should exist at all times
  replicas: 2
  selector:
    matchLabels:
      app: nodedb-app
  template: 
    metadata:
      labels:
        app: nodedb-app
    spec:
      containers:
      - name: nodedb-app
        image: roshanchaturpale/node-mongo-db:03

      - name: mongodb
        image: mongo



 
        
